/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      typography: {
        DEFAULT: {
          css: {
            "--tw-prose-body": "#52525b",
            "--tw-prose-headings": "#18181b",
            "--tw-prose-links": "#14b8a6",
            "--tw-prose-links-hover": "#0d9488",
            "--tw-prose-underline": "rgba(20,184,166,.2)",
            "--tw-prose-underline-hover": "#14b8a6",
            "--tw-prose-bold": "#18181b",
            "--tw-prose-counters": "#18181b",
            "--tw-prose-bullets": "#18181b",
            "--tw-prose-hr": "#f4f4f5",
            "--tw-prose-quote-borders": "#e4e4e7",
            "--tw-prose-captions": "#a1a1aa",
            "--tw-prose-code": "#3f3f46",
            "--tw-prose-code-bg": "hsla(240,5%,84%,.2)",
            "--tw-prose-pre-code": "#f4f4f5",
            "--tw-prose-pre-bg": "#18181b",
            "--tw-prose-pre-border": "transparent",
            "--tw-prose-th-borders": "#e4e4e7",
            "--tw-prose-td-borders": "#f4f4f5",
            "--tw-prose-invert-body": "#a1a1aa",
            "--tw-prose-invert-headings": "#e4e4e7",
            "--tw-prose-invert-links": "#2dd4bf",
            "--tw-prose-invert-links-hover": "#2dd4bf",
            "--tw-prose-invert-underline": "rgba(45,212,191,.3)",
            "--tw-prose-invert-underline-hover": "#2dd4bf",
            "--tw-prose-invert-bold": "#e4e4e7",
            "--tw-prose-invert-counters": "#e4e4e7",
            "--tw-prose-invert-bullets": "#e4e4e7",
            "--tw-prose-invert-hr": "rgba(63,63,70,.4)",
            "--tw-prose-invert-quote-borders": "#71717a",
            "--tw-prose-invert-captions": "#71717a",
            "--tw-prose-invert-code": "#d4d4d8",
            "--tw-prose-invert-code-bg": "hsla(240,6%,90%,.05)",
            "--tw-prose-invert-pre-code": "#f4f4f5",
            "--tw-prose-invert-pre-bg": "rgba(0,0,0,.4)",
            "--tw-prose-invert-pre-border": "hsla(240,6%,90%,.1)",
            "--tw-prose-invert-th-borders": "#3f3f46",
            "--tw-prose-invert-td-borders": "#27272a",
            color: "var(--tw-prose-body)",
            "line-height": "1.75rem",
          },
        },
        invert: {
          css: {
            "--tw-prose-body": "var(--tw-prose-invert-body)",
            "--tw-prose-headings": "var(--tw-prose-invert-headings)",
            "--tw-prose-links": "var(--tw-prose-invert-links)",
            "--tw-prose-links-hover": "var(--tw-prose-invert-links-hover)",
            "--tw-prose-underline": "var(--tw-prose-invert-underline)",
            "--tw-prose-underline-hover":
              "var(--tw-prose-invert-underline-hover)",
            "--tw-prose-bold": "var(--tw-prose-invert-bold)",
            "--tw-prose-counters": "var(--tw-prose-invert-counters)",
            "--tw-prose-bullets": "var(--tw-prose-invert-bullets)",
            "--tw-prose-hr": "var(--tw-prose-invert-hr)",
            "--tw-prose-quote-borders": "var(--tw-prose-invert-quote-borders)",
            "--tw-prose-captions": "var(--tw-prose-invert-captions)",
            "--tw-prose-code": "var(--tw-prose-invert-code)",
            "--tw-prose-code-bg": "var(--tw-prose-invert-code-bg)",
            "--tw-prose-pre-code": "var(--tw-prose-invert-pre-code)",
            "--tw-prose-pre-bg": "var(--tw-prose-invert-pre-bg)",
            "--tw-prose-pre-border": "var(--tw-prose-invert-pre-border)",
            "--tw-prose-th-borders": "var(--tw-prose-invert-th-borders)",
            "--tw-prose-td-borders": "var(--tw-prose-invert-td-borders)",
          },
        },
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
