query getPosts {
  posts {
    data {
      id
      attributes {
        slug
        title
        description
        publishedAt
        tags {
          data {
            id
            attributes {
              name
            }
          }
        }
      }
    }
    meta {
      pagination {
        total
      }
    }
  }
}
